# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20170826_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default='abc.mp3', upload_to=b''),
        ),
    ]
